apiVersion: apps/v1
kind: Deployment
metadata:
  name: harnessdemo-deployment
  namespace: harnessdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harnessdemo
  template:
    metadata:
      labels:
        app: harnessdemo
    spec:
      containers:
      - name: harnessdemo
        image: ghcr.io/dmitarb/cidemo:sha256-93adb781a5d7c11b8370c952fd5394d991d27a6c4b1809ca392748e623fbdf7e.sig
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: harnessdemo-service
  namespace: harnessdemo
spec:
  selector:
    app: harnessdemo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
